# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase Filter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
  pod 'Just'

  # Pods for Firebase Filter

  target 'Firebase FilterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Firebase FilterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
